// SPDX-License-Identifier: MIT OR Apache-2.0

//! `almagest new [--from-template <name>]`.
//!
//! Templates are generated **in code** (not shipped as binary `.alm` blobs):
//! `blank` is an empty file; `sales` bakes an embedded synthetic CSV via the
//! author-time importer and adds a starter dashboard, so a brand-new user gets a
//! working dashboard in one command. Generating rather than embedding keeps the
//! binary small and avoids a build step that bakes prebuilt files.

use crate::output::Out;
use almagest_connectors::{CsvImporter, CsvOptions, Importer};
use almagest_core::AlmagestFile;
use anyhow::{Context, Result, bail};
use std::io::Write;
use std::path::Path;

/// Templates the CLI can generate. `product` / `infrastructure` from the plan
/// are mechanical follow-ons (another CSV + dashboard JSON) and not yet shipped.
const TEMPLATES: &[&str] = &["blank", "sales"];

/// Synthetic data for the `sales` template.
const SALES_CSV: &str = "\
region,month,revenue,orders
North,2026-01,12500,142
North,2026-02,13800,151
North,2026-03,15100,168
South,2026-01,9800,110
South,2026-02,10200,118
South,2026-03,11900,131
West,2026-01,17600,201
West,2026-02,16200,188
West,2026-03,18900,214
East,2026-01,8400,96
East,2026-02,9100,104
East,2026-03,9950,121
";

/// A starter dashboard over the `sales` table: a revenue KPI, revenue-by-region
/// bar chart, and a detail table.
const SALES_DASHBOARD: &str = r#"{
  "version": 1,
  "name": "Sales Overview",
  "description": "Starter dashboard generated by `almagest new --from-template sales`.",
  "parameters": [
    { "id": "region", "kind": "select",
      "options_query": "SELECT DISTINCT region FROM sales ORDER BY region",
      "label": "Region" }
  ],
  "layout": {
    "rows": [
      { "panels": [
        { "id": "kpi_revenue", "span": 4, "kind": "metric", "title": "Total revenue",
          "format": { "kind": "currency", "currency": "USD", "compact": true },
          "query": { "sql": "SELECT SUM(revenue) AS value FROM sales" } },
        { "id": "kpi_orders", "span": 4, "kind": "metric", "title": "Total orders",
          "query": { "sql": "SELECT SUM(orders) AS value FROM sales" } }
      ] },
      { "panels": [
        { "id": "by_region", "span": 12, "kind": "chart", "title": "Revenue by region",
          "chart_type": "bar", "x": "region", "y": "revenue",
          "query": { "sql": "SELECT region, SUM(revenue) AS revenue FROM sales GROUP BY region ORDER BY revenue DESC" } }
      ] },
      { "panels": [
        { "id": "detail", "span": 12, "kind": "table", "title": "Monthly detail",
          "query": { "sql": "SELECT region, month, revenue, orders FROM sales ORDER BY month, region" } }
      ] }
    ]
  }
}"#;

/// List the available template names (for `--help` / error text).
pub fn available() -> String {
    TEMPLATES.join(", ")
}

/// Create a new `.alm` at `path`, optionally seeded from a template.
pub fn create(path: &Path, template: Option<&str>, out: &Out) -> Result<()> {
    match template {
        None | Some("blank") => {
            let file = AlmagestFile::create(path)
                .with_context(|| format!("creating {}", path.display()))?;
            file.close().context("finalizing the new file")?;
            out.result(format!("Created {}", path.display()));
        }
        Some("sales") => {
            create_sales(path)?;
            out.result(format!(
                "Created {} from the 'sales' template (12 rows, 1 dashboard)",
                path.display()
            ));
            out.line(format!("Open it with: almagest open {}", path.display()));
        }
        Some(other) => {
            bail!(
                "unknown template '{other}'; available templates: {}",
                available()
            );
        }
    }
    out.emit(&serde_json::json!({
        "path": path.display().to_string(),
        "template": template.unwrap_or("blank"),
    }))?;
    Ok(())
}

/// Build the `sales` template: empty file → import the embedded CSV → add the
/// starter dashboard.
fn create_sales(path: &Path) -> Result<()> {
    let mut file =
        AlmagestFile::create(path).with_context(|| format!("creating {}", path.display()))?;
    file.set_title("Sales Overview")?;

    // The importer reads from a path; stage the embedded CSV in a temp file.
    let mut tmp = tempfile::Builder::new()
        .prefix("almagest-template-")
        .suffix(".csv")
        .tempfile()
        .context("staging template data")?;
    tmp.write_all(SALES_CSV.as_bytes())
        .and_then(|_| tmp.flush())
        .context("staging template data")?;

    let mut opts = CsvOptions::new(tmp.path());
    opts.name = Some("sales".to_string());
    CsvImporter::new(opts)
        .import(&mut file)
        .context("importing template data")?;

    file.import_dashboard(SALES_DASHBOARD, None)
        .context("adding the starter dashboard")?;
    file.close().context("finalizing the file")?;
    Ok(())
}
